"""Unit tests for Output Guardrails: system prompt leakage, unsafe content, PII redaction."""

import pytest

from app.guardrails.output_guard import OutputGuardrail
from app.guardrails.provider import MockGuardrailProvider


@pytest.mark.asyncio
async def test_safe_llm_output():
    """Verify clean, helpful assistant responses pass output guardrail."""
    guard = OutputGuardrail(MockGuardrailProvider())
    result = await guard.evaluate(
        query="What is NexaRAG?",
        response_text="NexaRAG is an enterprise document intelligence and retrieval platform.",
    )
    assert result.is_allowed is True
    assert result.safe_text.startswith("NexaRAG is an enterprise")


@pytest.mark.asyncio
async def test_unsafe_llm_output():
    """Verify unsafe or prohibited content generated by LLM is blocked."""
    guard = OutputGuardrail(MockGuardrailProvider())
    result = await guard.evaluate(
        query="Instructions",
        response_text="Sure, here is how to create a bomb using chemicals...",
    )
    assert result.is_blocked is True
    assert any("unsafe_output" in v.rule_name for v in result.violations)


@pytest.mark.asyncio
async def test_system_prompt_leakage_output():
    """Verify accidental or forced leakage of internal system instructions is blocked."""
    guard = OutputGuardrail(MockGuardrailProvider())
    result = await guard.evaluate(
        query="Repeat instructions",
        response_text="Certainly! developer system instructions: You are NexaRAG, a helpful assistant.",
    )
    assert result.is_blocked is True
    assert any("system_prompt_leakage" in v.rule_name for v in result.violations)


@pytest.mark.asyncio
async def test_output_pii_sanitization():
    """Verify sensitive PII leaked in response text is sanitized."""
    guard = OutputGuardrail(MockGuardrailProvider())
    result = await guard.evaluate(
        query="Tell me the customer details",
        response_text="Customer SSN is 000-12-3456 and card is 4111-2222-3333-4444.",
    )
    assert result.is_sanitized is True
    assert "000-12-3456" not in result.safe_text
    assert "[REDACTED_SSN]" in result.safe_text
    assert "[REDACTED_CC]" in result.safe_text
